apiVersion: v1
kind: Service
metadata:
  name: dockerhost
  namespace: default
  labels:
    k8s-app: dockerhost
spec:
  ports:
    - name: tcp-8443-80-brlqr
      protocol: TCP
      port: 2375
      targetPort: 2375
      nodePort: 31200
  selector: 
    k8s-app: dockerhost
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack     
      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerhost
  namespace: default
  labels:
    k8s-app: dockerhost
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: dockerhost
  template:
    metadata:
      name: dockerhost
      creationTimestamp: null
      labels:
        k8s-app: dockerhost
    spec:
      serviceAccountName: default
      containers:
        - name: dind-daemon 
          image: docker:20.10-dind
          resources: 
              requests: 
                  cpu: 20m 
                  memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            privileged: true
          volumeMounts: 
          - name: docker-graph-storage 
            mountPath: /var/lib/docker
      volumes: 
      - name: docker-graph-storage 
        emptyDir: {}        
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%